const USERNAME = "YOUR_INSTAGRAM_USER_NAME",
    PASSWORD = "YOUR_INSTAGRAM_PASSWORD",
    SHEET_ID = 'GOOGLE_SHEET_ID',
    SHEET_NAME = 'SHEET_NAME';


export {
    USERNAME,
    PASSWORD,
    SHEET_ID,
    SHEET_NAME
};
